### PR TITLE
Partial auto refresh/HMR

### PR DESCRIPTION
**Pull request by jdf221**
Adds HMR support to allow partials to be auto refreshed when their content is changed.

Todo:
* Add config option to disable or change to full browser refresh
* Write tests

(More info: https://github.com/alexlafroscia/vite-plugin-handlebars/issues/2#issuecomment-800986651)

### CODE REVIEW

**Comment by alexlafroscia** [comment]
I really appreciate the effort you've put into this!

I'm wondering if we can start with a first pass that simplifies things and just always performs a full page reload instead of trying to hot-reload when a partial changes. The code required for doing the HMR replacement just adds _so_ much complexity to this plugin, and honestly, I am not sure I want to maintain that going forward.

Is there a way to trigger a page refresh from the `ViteDevServer` object on the server, without having to ship _any_ client code for the plugin? I know you can dispatch a web socket event for custom events, but is there an event that can be sent to just reload the whole page?

**Comment by jdf221** [comment]
> is there an event that can be sent to just reload the whole page?

Looks like there is: https://github.com/vitejs/vite/blob/main/packages/vite/src/client/client.ts#L90

Tested it out and the only code required is the `handleHotUpdate` function and sending the `full-reload` event inside it.

Personally i dislike the white flash that comes with a full page reload but can understand not wanted to deal with the complicated code.

**Comment by alexlafroscia** [comment]
> Personally i dislike the white flash that comes with a full page reload. Definitely a nitpicky unimportant preference though

I wouldn’t say that! HMR is _really_ cool. I work day-to-day in a framework that doesn’t support HMR and am jealous of the communities that have it! I am just weary of complicating this plugin so much for what is really a small optimization. HMR really shines when you can keep state in your application and swap out the code without losing that state, which isn’t really relevant for these Handlebars partials. 

I think that starting with a full page-refresh will be a good first step, and if over time it seems like there’s a lot of requests for proper HMR, we can re-visit this PR!

Thanks for finding that `full-reload` event — that’s perfect. Do you want to update this PR, or do you want me to take a crack at implementing it based on the work you’ve done?

**Comment by alexlafroscia** [comment]
Another few thoughts:

* Any idea how to test this? Our current tests assume a one-time build; I wonder how we can write tests for something that requires the server to be “running” while we interact with the files on the file-system. If you’re not sure, I can look into this
* I think Handlebars has a means of un-registering a partial. We should probably do that when we detect that the partial has changed, before registering the updated implementation. I’m not sure what the implications of not doing that are, but it seems like the safe thing to do!
*

**Pull request closed without merging**
